version: '3.8'

services:
  sso_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DATABASE_NAME=sso_db
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - mongodb
    networks:
      - sso_network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sso_network

volumes:
  mongodb_data:

networks:
  sso_network:
    driver: bridge

