services:
  sso_service:
    build: ./sso_service
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DATABASE_NAME=sso_db
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - mongodb
    networks:
      - app_network

  st_dom_service:
    build: ./st_dom_service
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DATABASE_NAME=st_dom_db
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - PORT=8081
      - GIN_MODE=release
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge

